name: tflite
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.4.2
  - python=3.8.6
  - pip:
    - matplotlib==3.3.3
    - numpy==1.19.3
    - opencv-python==4.5.1.48
    - pandas==1.2.0
    - tensorflow==2.4.0
    - tensorflow-model-optimization==0.5.0
    - scipy==1.6.0
